### ISSUE TITLE
Building wheel for image-blender (pyproject.toml) ... error

### ISSUE THREAD

**Issue by Hathan67** [psd-tools/image-blender#3]
those who are trying to install having this build issue try resolve that with Installing this .whl file

**Comment by EvgenKo423** [comment]
This is not a real error and it may be caused by lots of different issues. If you have some installation problems, please attach a complete installation log.

Also this package currently only comes as a source distribution, so you will need to [install a C compiler](https://wiki.python.org/moin/WindowsCompilers) to build it.
There is no `.whl` file attached to your issue (because GitHub doesn't accept this format) and this is not a good idea in general as it depends on your OS and Python version. You're trying to solve consequences instead of a real problem.
